language: python
python:
- '3.7'
dist: xenial
sudo: true
install:
  - pip install -r requirements.txt
  - pip install codecov
before script:
  - cd Source
script:
 - coverage run Source/setup.py test
after_success:
  - codecov
